source "https://rubygems.org"

gem "httparty"
gem 'sinatra'
gem 'json'
gem 'rack'
gem 'rack-contrib'
gem 'aws-record'
gem 'rake'
gem 'rubysl-base64'

group :test do
  gem "test-unit"
  gem "mocha"
  gem "rspec"
  gem "rack-test"
end
